### ISSUE TITLE
Date-Time Format Issue on Save

### ISSUE THREAD

**Issue by hreineck** [EasyDynamics/oscal-rest-service#99] opened 2022-06-01 02:53 UTC
When saving any changes via the REST Service, any date-time fields are filled with a format like:
`2021-02-25T00:00:00.00-04:00`

This causes a 500 error when trying to view in the OSCAL Viewer, presumably because that format is incorrect.
Setting the date manually to the format:
`2021-02-25T00:00` instead seems to be the proper format.

**Comment by rgauss** [comment] 2022-06-02 17:16
The first format should be a valid [dateTime-with-timezone](https://pages.nist.gov/OSCAL/reference/datatypes/#datetime-with-timezone), and this seems to be working for me.

Are there specific date-time fields you're noticing that aren't working, and can you point to an example?

**Comment by laurelmay** [comment] 2022-06-02 17:33
A few more questions to help narrow down the cause:
 - Does the error occur on the POST/PUT request (actually processing the new data and/or storing) or on the GET (loading the data back from disk)?
 - Are you able to reproduce in a scenario where you can pull the stack trace from Spring?
 - Is this actually a 500 error that you get for the service? Or another "Yikes"/unmounting of the OSCAL Viewer?
 - What browser (and version) are you using?
 - Are you using the Docker container or another means to run the server?

**Comment by mikeisen1** [comment] 2022-06-03 19:13
@kylelaker, I tested it out and got the error. Here are my results.

How the application was run: Docker
Browser: Google Chrome Version 101.0.4951.67 64-bit
Request type: PATCH (Update of SSP version)
Error Message in Console: `Failed to load resource: the server responded with a status of 500 ()`
Error Message in Viewer:  `Yikes! Something went wrong loading the OSCAL data.
500`

Here is the spring logs of the error. The top line is the first entry after the PATCH request was made.
![error log](https://user-images.githubusercontent.com/43248318/171933288-0e2f1ccd-472a-49eb-b9ac-d31df937d9c7.png)

Here is the stack trace:
![save error stack trace](https://user-images.githubusercontent.com/43248318/171932206-91bd0f3a-abed-4cca-a40e-b21518cce70b.png)

**Comment by rgauss** [comment] 2022-06-03 19:19
@mikeisen1, can you also give info on:
- OS version
- Docker version
- Run command used
- When the image you're using was last pulled (or what sources built from)

**Comment by laurelmay** [comment] 2022-06-03 19:20
@mikeisen1 Thanks for that report! So while there is an issue there, I think it's actually more related to #98 (because this is an `AccessDeniedException`). But I am really interested to hear more

**Comment by mikeisen1** [comment] 2022-06-03 19:27
> @mikeisen1, can you also give info on:
> 
> * OS version
> * Docker version
> * Run command used
> * When the image you're using was last pulled (or what sources built from)

- OS version: Windows 11 Version 21H2
- Docker version: Docker version 20.10.12, build 20.10.12-0ubuntu2~20.04.1
- Build command (run after starting the docker daemon): `docker build --build-arg OSCAL_REACT_GIT_BRANCH=develop --build-arg OSCAL_REST_SERVICE_GIT_BRANCH=develop --tag oscal-editor-all-in-one .`
- Run command: `docker run -p 8080:8080 -v "$(pwd)"/../../oscal-demo-content:/app/oscal-content oscal-editor-all-in-one`

**Comment by hreineck** [comment] 2022-06-07 18:02
Upon further investigation, this is my bad. I was using an older version of my Docker image which hadn't been updated to liboscal-java 1.0.2. I haven't been able to reproduce this after updating so I'm assuming the issue was a discrepancy in going between the two versions.

**Comment by laurelmay** [comment] 2022-06-07 18:10
@hreineck I am going to go ahead and close this issue then (the error around date-time format); if we do find that this can be reproduced then we'll reopen it.

@mikeisen1 if you continue to experience your crash, we likely want to track that in a separate issue that includes the additional information you provided as well as the permissions of files in your environment.

**Closed as not planned by laurelmay** 2022-06-07 18:10 UTC
